version: '3.9'

services:
  redis:
    image: redis:latest
    container_name: app-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: files-analyzer
    depends_on:
      redis
        condition: service_started
    env_file:
      - .env
    ports:
      - "8000:8000"   
    volumes:
      - .:/app       # чтобы можно было править код на хосте и видеть изменения
    command: ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-scheduler
    depends_on:
      - app
      - redis
    env_file:
      - .env
    command: python scheduler.py

volumes:
  redis_data:
